language: ruby
rvm:
  - 1.9.3
  - 2.0.0
cache: bundler
notifications:
  irc:
    channels:
      - "irc.freenode.org#berkshelf"
    skip_join: true
    use_notice: true
bundler_args: --without guard
before_install:
  - sudo apt-get install -qq libarchive12 libarchive-dev
before_script:
  - echo "StrictHostKeyChecking no" > ~/.ssh/config
  - git config --global user.email "ci@berkshelf.com"
  - git config --global user.name "Berkshelf"
script: bundle exec thor spec:ci
